plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "chatutils" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}


repositories {
    maven { url = "https://api.modrinth.com/maven" }
}

configurations {
    testCompileClasspath.extendsFrom minecraftCommonNamedCompile, minecraftClientOnlyNamedCompile
    testRuntimeClasspath.extendsFrom minecraftCommonNamedRuntime, minecraftClientOnlyNamedRuntime
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "maven.modrinth:yacl:3.9.5+26.2-fabric"
    include "maven.modrinth:yacl:3.9.5+26.2-fabric"
    implementation "maven.modrinth:modmenu:20.0.1"
    implementation "maven.modrinth:placeholder-api:3.1.0-beta.1+26.2"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    testImplementation platform("org.junit:junit-bom:5.12.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

sourceSets {
    test {
        compileClasspath += sourceSets.client.output
        runtimeClasspath += sourceSets.client.output
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
    }
}
